### ISSUE TITLE
No Module named 'fcntl'

### ISSUE THREAD

**Issue by ianxxiao** [Netflix/metaflow#46] opened 2019-12-11 15:12 UTC
What I did:
- I installed using `pip install metaflow` on Windows 10
- typed `metaflow` 
- errored "No module named 'fcntl'"

**Comment by savingoyal** [comment] 2019-12-11 17:12
Duplicate of https://github.com/Netflix/metaflow/issues/23

**Closed** 2019-12-11 20:10 UTC
Labels: duplicate, help wanted
